### ISSUE TITLE
Integrate ECharts JS plot library in DFLib

### ISSUE THREAD

**Issue by andrus** [dflib/dflib#285]
Let's integrate Apache ECharts to DFLib. The charts will be rendered as JS snippets that can be displayed in the UI. The first UI target will be Jupyter notebooks. 

Note that ECharts has an enormous number of configuration options. In this version, we will cover a small subset of them, and we'll expand it as we go.

**Comment by axkr** [comment]
> Let's integrate Apache ECharts to DFLib. The charts will be rendered as JS snippets that can be displayed in the UI. The first UI target will be Jupyter notebooks. 

How do you plan to generate the JS? Do you use https://echarts.icepear.org/ or do you create your own library?

**Comment by andrus** [comment]
Ah, interesting. Wasn't aware of this lib. I already have something working [here](https://github.com/dflib/dflib/tree/285), though the API is work in progress and is going to change:

<img width="694" alt="image" src="https://github.com/dflib/dflib/assets/42668/6563cfd8-ce29-4689-8274-76ba2a677d7a">

Not using the library saves some extra dependencies and makes things more "native" (able to work directly with the DataFrame), so I may stay on this path, but I really like how they classified ECharts coordinate types, and otherwise made dealing with "options" more sane. So thanks a lot for the pointer.

**Comment by andrus** [comment]
Just merged the initial integration. It supports basic Cartesian charts (line, scatter, bar) and a number of useful configuration options. We will continue extending it in this and other releases. An example of time series:

```
t                     v1 v2
------------------- ---- --
2024-01-01             3 20
2024-01-02             5  6
2024-02-03             2 11
2024-02-10             4 11
2024-02-12             2 15
2024-02-14             3 14
2024-02-15             4 13
2024-02-15T03:05:06    5 12
2024-02-20          11.5  2
```

```java
ECharts
    .chart("temp, °C")
    .sizePixels(600, 350)
    .series(SeriesOpts.line().smooth().areaStyle(), "v1", "v2")
    .xAxis("t", Axis.time())
    .yAxis(Axis.value().boundaryGap(false).label(AxisLabel.create().formatter("{value} °C")))
    .toolbox(Toolbox.create().featureDataZoom().featureSaveAsImage())
    .legend()
    .plot(df)
```

![temp, °C(1)](https://github.com/dflib/dflib/assets/42668/3417108f-9575-4123-8c76-c2ebf215beff)
