### ISSUE TITLE
No Github release created during Maven deploy

### ISSUE THREAD

**Issue by andrus** [dflib/dflib#354]
While we have `release.yml` per #323 with intent to create a new GitHub "release" when we are doing a Maven release, doesn't look like it got triggered when I did RC1 release today. Something to investigate.

**Comment by stariy95** [comment]
This rule in the `release.yml` is the problem: 
```yml
on:
  push:
    tags:
      - '[0-9]+.[0-9]+*'
```

We either change this rule to use a tag format currently used by default (like `dflib-parent-1.0.0-RC1`), or change tag format for future releases.

**Comment by andrus** [comment]
I'd rather we change the rule and keep the tag format
