### ISSUE TITLE
When will be the release  v1.0.0 available in Maven Central

### ISSUE THREAD

**Issue by Hemasundararaopottangi** [dflib/dflib#389]
Hi ,
When will be the release  v1.0.0 available in Maven Central , currently  v1.0.0-RC1 is available in Maven Central ,

Regards,
Hema.

**Comment by andrus** [comment]
Hi Hema, we are debating whether the next release should be RC2 or 1.0.0 (GA). Depending on the decision, the GA should happen within 2-7 weeks. And BTW, it is entirely safe to use RC1. The API is frozen on this branch, so if you start with it, the GA will be a drop-in replacement.

**Comment by andrus** [comment]
Hi @Hemasundararaopottangi , a bugfix `1.0.0-RC2` got released today - https://github.com/dflib/dflib/discussions/395  . It is a drop-in replacement of RC1. `1.0.0` GA should happen mid-December.
