### ISSUE TITLE
provide load(URI) method for csv, json etc.

### ISSUE THREAD

**Issue by maxandersen** [dflib/dflib#412]
would be nice to just do CsvLoader.load(URI.of("https://some.csv/fileplace.csv")); instead of the needed multi nested try/finally needed today ;)

**Comment by andrus** [comment]
Yeah, good point. We are in a process of defining a better "connector architecture" in 2.0 (separating data formats from the way you obtain the data). Let me see if I can sneak the HTTP connector into 1.1 though

**Comment by andrus** [comment]
Ok, so with the 1.1.0 release that was just posted today, you can now do a couple of things:

```java
// 1. for simple public URLs
var df1 = Csv.loader().load(ByteSource.ofUrl("https://example.org/my.csv));

// 2. for more complex cases to assemble URL from parts and provide auth headers
var df2 = Csv.loader().load(Http
    .of("https://example.org/")
    .path("my.csv")
    .header("Authorization", "Bearer abcdefghijklmnop")
    .source()
);
```
